version: "3.4"

services:
    api:
        build:
          context: .
          dockerfile: Dockerfile
        ports:
          - "8080:80"
          - "7180:7180"
        environment:
          - ASPNETCORE_ENVIRONMENT=Development
          - ConnectionStrings__DevConnection=Server=db;Database=master;User=sa;Password=S3cur3P@ssW0rd!;TrustServerCertificate=True;
        depends_on:
          - db

    db:
        image: "mcr.microsoft.com/mssql/server:2022-latest"
        ports:
          - "1433:1433"

        environment:
            SA_PASSWORD: "S3cur3P@ssW0rd!"
            ACCEPT_EULA: "Y"

    gui:
        image: "ghornon/ebilety-gui:latest"
        ports:
          - "80:80"
        depends_on:
          - api